// Central catalog of structured logging event IDs.
// Naming convention: DOMAIN_ACTION_RESULT or SHORT semantic tokens.
// Keep values stable; changing requires documentation update.

const events = {
  JOB_COMPLETED: 'SIM_JOB_COMPLETED',
  JOB_FAILED: 'SIM_JOB_FAILED',
  IDEMPOTENCY_SKIP: 'SIM_IDEMPOTENCY_SKIP',
  ACTIVITY_THINNING_APPLIED: 'SIM_ACTIVITY_THINNING_APPLIED',
  ACTIVITY_THINNING_ERROR: 'SIM_ACTIVITY_THINNING_ERROR',
  HUBSPOT_OP_FAILED: 'HS_OP_FAILED',
  QUEUE_WORKER_COMPLETED: 'QUEUE_WORKER_COMPLETED',
  QUEUE_WORKER_FAILED: 'QUEUE_WORKER_FAILED',
  DLQ_ENQUEUE_FAILED: 'DLQ_ENQUEUE_FAILED',
  DLQ_REPLAY: 'DLQ_REPLAY',
  DLQ_REPLAY_RATE_LIMIT: 'DLQ_REPLAY_RATE_LIMIT',
  ABORT_SOFT: 'SIM_ABORT_SOFT',
  ABORT_FORCE: 'SIM_ABORT_FORCE',
  RATE_LIMIT_HIT: 'HS_RATE_LIMIT_HIT',
  RETRY_SCHEDULED: 'HS_RETRY_SCHEDULED',
  CIRCUIT_TRIP: 'HS_CIRCUIT_TRIP',
  CIRCUIT_RECOVER: 'HS_CIRCUIT_RECOVER',
  AI_GENERATION_SUCCESS: 'AI_GEN_SUCCESS',
  AI_GENERATION_FALLBACK: 'AI_GEN_FALLBACK',
  AI_GENERATION_ERROR: 'AI_GEN_ERROR',
  AI_GENERATION_RETRY: 'AI_GEN_RETRY'
}

module.exports = events
module.exports.default = events
